name: Deploy Frontend

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: self-hosted
    environment: dev   # 👈 pega as variáveis do Environment DEV no GitHub
    env:
      APP_STAGE: ${{ vars.APP_STAGE }}
      NEXT_PUBLIC_API_BASE: ${{ vars.NEXT_PUBLIC_API_BASE }}
      API_BASE: ${{ vars.API_BASE }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Build do projeto (sempre prod, mas com env de DEV)
        run: npm run build

      - name: Deploy com PM2
        run: |
          pm2 restart mangazinho-fe --update-env || pm2 start "npm run start" --name "mangazinho-fe"
          pm2 save
