name: Deploy Frontend

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: self-hosted  # 👈 roda no runner que você registrou na VM
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Build do projeto
        run: npm run build

      - name: Deploy com PM2
        run: |
          pm2 restart mangazinho-fe --update-env || pm2 start "npm run start" --name "mangazinho-fe"
          pm2 save
